import * as THREE from 'https://esm.sh/three@0.180.0';

const D=window.FIELD_LAB||{}, view=document.querySelector('#view-lab'), wrap=view?.querySelector('.viewer-wrap'), oldCanvas=document.querySelector('#simCanvas');
if(!view||!wrap||!oldCanvas||document.querySelector('#core3dV10Stage')){
  // no-op
}else{
  wrap.classList.add('core3d-v10-active');
  const stage=document.createElement('div');stage.id='core3dV10Stage';stage.className='core3d-v10-stage';
  stage.innerHTML='<div class="core3d-v10-badge"><span class="pill">True 3D</span><span class="pill" id="core3dPerf">high-DPI</span></div><div class="core3d-v10-help">Drag to rotate · wheel/pinch to zoom · use the existing controls to change the physics</div>';
  wrap.prepend(stage);
  const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;stage.insertBefore(renderer.domElement,stage.firstChild);
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x06111d);scene.fog=new THREE.Fog(0x06111d,18,55);
  const camera=new THREE.PerspectiveCamera(42,1,.1,120);let yaw=-.6,pitch=.36,dist=14,drag=false,lx=0,ly=0;
  function cam(){const cp=Math.cos(pitch),sp=Math.sin(pitch),cy=Math.cos(yaw),sy=Math.sin(yaw);camera.position.set(dist*cp*sy,dist*sp+1,dist*cp*cy);camera.lookAt(0,0,0)}cam();
  scene.add(new THREE.HemisphereLight(0xc9edff,0x132033,1.8));const key=new THREE.DirectionalLight(0xffffff,2.8);key.position.set(8,12,7);key.castShadow=true;key.shadow.mapSize.set(2048,2048);scene.add(key);const rim=new THREE.DirectionalLight(0x6bbcff,1.1);rim.position.set(-8,5,-6);scene.add(rim);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(40,40),new THREE.MeshStandardMaterial({color:0x091827,roughness:.92,metalness:.02}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.65;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(40,40,0x28445d,0x14273a);grid.position.y=-2.63;grid.material.transparent=true;grid.material.opacity=.25;scene.add(grid);
  renderer.domElement.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;lx=e.clientX;ly=e.clientY;yaw-=dx*.006;pitch=Math.max(-.15,Math.min(1.18,pitch-dy*.005));cam()});renderer.domElement.addEventListener('pointerup',()=>drag=false);renderer.domElement.addEventListener('pointercancel',()=>drag=false);renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();dist=Math.max(7,Math.min(27,dist+e.deltaY*.012));cam()},{passive:false});
  const metallic=(c,r=.26,m=.76)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m}), plastic=(c,r=.5)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:.04}), glow=(c,o=.65)=>new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o});
  const models=[];const dyn=[];const mark=o=>(o.userData.coreV10=1,models.push(o),o);
  const add=o=>{scene.add(o);return mark(o)};
  function box(w,h,d,mat,x=0,y=0,z=0){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return add(o)}
  function sphere(r,mat,x=0,y=0,z=0){const o=new THREE.Mesh(new THREE.SphereGeometry(r,40,28),mat);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;return add(o)}
  function cyl(r,h,mat,x=0,y=0,z=0,axis='y'){const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,36),mat);o.position.set(x,y,z);if(axis==='x')o.rotation.z=Math.PI/2;if(axis==='z')o.rotation.x=Math.PI/2;o.castShadow=o.receiveShadow=true;return add(o)}
  function torus(r,t,mat,x=0,y=0,z=0,rx=Math.PI/2){const o=new THREE.Mesh(new THREE.TorusGeometry(r,t,16,64),mat);o.position.set(x,y,z);o.rotation.x=rx;o.castShadow=true;return add(o)}
  function arrow(dir,origin,len,col){return add(new THREE.ArrowHelper(dir.clone().normalize(),origin,len,col,.3,.16))}
  function clear(){models.splice(0).forEach(o=>{scene.remove(o);o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m.dispose?.());else o.material?.dispose?.()});dyn.length=0}
  function simId(){const title=document.querySelector('#simTitle')?.textContent?.trim();return Object.entries(D.simulations||{}).find(([,s])=>s.title===title)?.[0]||'fieldCompare'}
  function vals(){const id=simId(),def=D.simulations?.[id],inputs=[...document.querySelectorAll('#simControls input')],out={};(def?.controls||[]).forEach((c,i)=>out[c.id]=Number(inputs[i]?.value??c.value));return out}
  let current='';
  function build(){const id=simId(),v=vals();current=id;clear();
    if(id==='fieldCompare')fieldCompare(v); else if(id==='gravity')gravity(v); else if(id==='orbit')orbit(v); else if(id==='electric')electric(v); else if(id==='capacitor')capacitor(v); else if(id==='discharge')discharge(v); else if(id==='magWire')magWire(v); else if(id==='particle')particle(v); else if(id==='flux')flux(v); else if(id==='induction')induction(v); else if(id==='ac')ac(v); else transformer(v);
  }
  function fieldCompare(v){const sep=3.4;const a=sphere(1.05,plastic(0x4079a7,.72),-sep,0,0),b=sphere(.72,plastic(0xd45555,.38),sep,0,0);for(let i=0;i<14;i++){const ang=i/14*Math.PI*2;arrow(new THREE.Vector3(-Math.cos(ang),0,-Math.sin(ang)),new THREE.Vector3(-sep+2*Math.cos(ang),0,2*Math.sin(ang)),1.25,0x77d7ff);arrow(new THREE.Vector3(Math.cos(ang),0,Math.sin(ang)),new THREE.Vector3(sep+.9*Math.cos(ang),0,.9*Math.sin(ang)),1.45,0xf09b8e)}const probe=sphere(.18,plastic(0x76e7a0,.25),0,1.3,0);dyn.push({type:'float',o:probe,amp:.18,rate:1.4,baseY:1.3},{type:'spin',o:a,rate:.1},{type:'spin',o:b,rate:-.16})}
  function gravity(v){const p=sphere(2.15,plastic(0x2f75ad,.72),0,0,0),probe=sphere(.2,plastic(0x77e7a0,.28),4.8,0,0);for(let i=0;i<18;i++){const a=i/18*Math.PI*2;arrow(new THREE.Vector3(-Math.cos(a),0,-Math.sin(a)),new THREE.Vector3(4.4*Math.cos(a),0,4.4*Math.sin(a)),1.1,0x76cfff)}for(let r=3;r<6.5;r+=1.1)torus(r,.014,glow(0x93c9e8,.35),0,0,0,Math.PI/2);dyn.push({type:'radial',o:probe,r:4.8,rate:.38},{type:'spin',o:p,rate:.08})}
  function orbit(v){const p=sphere(2.0,plastic(0x2d73af,.7),0,0,0),r=4.2+((v.radius||8)-6.6)/(25-6.6)*2.1;torus(r,.02,glow(0x68cfff,.55),0,0,0,Math.PI/2);const sat=box(.48,.28,.7,metallic(0xd7e5ef,.22,.85),r,0,0);box(.9,.04,.36,plastic(0x244f86,.43),r,0,.6);box(.9,.04,.36,plastic(0x244f86,.43),r,0,-.6);const fg=arrow(new THREE.Vector3(-1,0,0),new THREE.Vector3(r,0,0),1.25,0x78e6a1),vv=arrow(new THREE.Vector3(0,0,1),new THREE.Vector3(r,0,0),1.4,0xf2c86b);dyn.push({type:'orbit',o:sat,r,rate:.36,fg,vv},{type:'spin',o:p,rate:.07})}
  function electric(v){const q=v.charge||4,pos=plastic(0xd45757,.3),neg=plastic(0x5278c9,.3);const src=sphere(.8,q>=0?pos:neg,-3.5,0,0),probe=sphere(.2,plastic(0x78e6a1,.25),0,1.1,0);for(let i=0;i<16;i++){const a=i/16*Math.PI*2,sgn=q>=0?1:-1;arrow(new THREE.Vector3(sgn*Math.cos(a),0,sgn*Math.sin(a)),new THREE.Vector3(-3.5+Math.cos(a),0,Math.sin(a)),1.6,0x6ed4ff)}box(.18,4.6,4.8,metallic(0xb9c8d5,.2,.9),2.0,0,0);box(.18,4.6,4.8,metallic(0x9caabb,.2,.9),4.3,0,0);for(let y=-1.8;y<=1.8;y+=.9)for(let z=-1.6;z<=1.6;z+=.9)arrow(new THREE.Vector3(1,0,0),new THREE.Vector3(2.3,y,z),1.7,0x8bdcff);dyn.push({type:'float',o:probe,baseY:1.1,amp:.28,rate:1.2},{type:'spin',o:src,rate:.18})}
  function capacitor(v){const gap=.65+((v.gap||.002)-.0005)/.0045*1.25,scale=.8+((v.area||.01)-.002)/.028*.9;const left=box(.16,4*scale,4*scale,metallic(0xc2ccd5,.18,.9),-gap,0,0),right=box(.16,4*scale,4*scale,metallic(0xa5b2c0,.18,.9),gap,0,0);const d=box(Math.max(.05,gap*1.2),3.5*scale,3.5*scale,new THREE.MeshPhysicalMaterial({color:0x69d7c5,transparent:true,opacity:.18,roughness:.18,transmission:.45}),0,0,0);const pts=[];for(let y=-1.5;y<=1.5;y+=.6)for(let z=-1.5;z<=1.5;z+=.6)pts.push(sphere(.045,glow(0x89dcff,.75),-gap+.2,y*scale,z*scale));dyn.push({type:'chargePulse',arr:pts,rate:1.8},{type:'dielectric',o:d,frac:Math.min(1,Math.max(0,((v.er||1)-1)/7))})}
  function discharge(v){const tau=(v.R||4700)*(v.C||470)*1e-6;const board=box(8,.16,4,plastic(0x172737,.82),0,-1.4,0);const cap1=box(.13,2.0,1.5,metallic(0xbcc8d2,.18,.88),1.0,0,0),cap2=box(.13,2.0,1.5,metallic(0xa7b3bf,.18,.88),1.7,0,0);const resistor=box(1.7,.42,.55,plastic(0xd9b06b,.55),-1.4,0,0);cyl(.06,2.2,metallic(0xd47837,.22,.85),-3.2,0,0,'x');cyl(.06,2.2,metallic(0xd47837,.22,.85),3.2,0,0,'x');const pulses=[];for(let i=0;i<12;i++)pulses.push(sphere(.08,glow(0x6ed4ff,.8),-3+i*.55,.45,0));dyn.push({type:'rc',arr:pulses,tau,cap:[cap1,cap2],rate:.8})}
  function magWire(v){box(2.1,2.3,4.8,plastic(0xbd4d4d,.42),-2.6,1.55,0);box(2.1,2.3,4.8,plastic(0x4d73bd,.42),-2.6,-1.55,0);for(let x=-1.2;x<=2.8;x+=1.0)for(let z=-1.8;z<=1.8;z+=1.2)arrow(new THREE.Vector3(0,-1,0),new THREE.Vector3(x,1.15,z),2.3,0x68cfff);const wire=cyl(.11,5.3,metallic(0xd47a35,.2,.88),.7,0,0,'x'),force=arrow(new THREE.Vector3(0,0,Math.sign(v.I||1)),new THREE.Vector3(.6,.4,0),1.5,0x78e6a1);dyn.push({type:'wire',o:wire,arrow:force,I:v.I||0,rate:1.8})}
  function particle(v){for(let x=-5;x<=5;x+=1.2)for(let z=-3;z<=3;z+=1.2)arrow(new THREE.Vector3(0,-1,0),new THREE.Vector3(x,1.5,z),2.5,0x68cfff);const r=Math.max(1.4,Math.min(4.8,2.7*((v.speed||2)/2)/((v.B||.2)/.2))),curve=new THREE.EllipseCurve(0,0,r,r,0,Math.PI*2,false,0),pts=curve.getPoints(160).map(p=>new THREE.Vector3(p.x,0,p.y));const path=add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:0xc8a8ff,transparent:true,opacity:.65})));const p=sphere(.19,plastic((v.chargeSign||1)>0?0xf0d36b:0x8eb5ff,.25),pts[0].x,0,pts[0].z);dyn.push({type:'path',o:p,pts,rate:1.0,sign:v.chargeSign||1})}
  function flux(v){for(let x=-5;x<=5;x+=1.3)for(let z=-3;z<=3;z+=1.3)arrow(new THREE.Vector3(0,-1,0),new THREE.Vector3(x,1.6,z),2.7,0x68cfff);const coil=torus(2.2,.09,metallic(0xd47a35,.2,.88),0,0,0,0);coil.rotation.z=(v.angle||30)*Math.PI/180;dyn.push({type:'wobble',o:coil,base:coil.rotation.z,amp:.08,rate:.9})}
  function induction(v){for(let x=-5;x<=5;x+=1.4)for(let z=-3;z<=3;z+=1.4)arrow(new THREE.Vector3(0,-1,0),new THREE.Vector3(x,1.6,z),2.7,0x68cfff);const coil=torus(2.0,.09,metallic(0xd47a35,.2,.88),0,0,0,0);dyn.push({type:'rotate',o:coil,rate:Math.max(.2,v.f||1)*1.3})}
  function ac(v){const scope=box(7.8,4.5,1.25,plastic(0x182b3e,.62),0,0,0),screen=box(6.4,3.1,.08,plastic(0x061018,.2),0,0,.67);const mat=new THREE.LineBasicMaterial({color:0x6ed4ff});const pts=[];for(let i=0;i<180;i++){const x=-3+i/179*6,y=Math.sin(i/179*Math.PI*6)*1.1;pts.push(new THREE.Vector3(x,y,.75))}const wave=add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),mat));const dot=sphere(.11,glow(0x9ff4ff,.95),-3,0,.77);dyn.push({type:'wave',o:dot,pts,rate:Math.max(.4,(v.f||20)/20)})}
  function transformer(v){const core=metallic(0x65717e,.48,.64);box(6,.65,.9,core,0,2.15,0);box(6,.65,.9,core,0,-2.15,0);box(.65,4.3,.9,core,-2.7,0,0);box(.65,4.3,.9,core,2.7,0,0);const p=Math.max(5,Math.round((v.Np||500)/100)),s=Math.max(5,Math.round((v.Ns||1000)/140));const pm=metallic(0xd47a35,.22,.86),sm=metallic(0x5aaee0,.22,.86),coils=[];for(let i=0;i<p;i++)coils.push(torus(.72,.045,pm,-2.7,-1.45+i*(2.9/(p-1||1)),0,Math.PI/2));for(let i=0;i<s;i++)coils.push(torus(.72,.045,sm,2.7,-1.45+i*(2.9/(s-1||1)),0,Math.PI/2));const pulse=sphere(.16,glow(0x78e6a1,.8),0,2.15,0);dyn.push({type:'corePulse',o:pulse,rate:1.1,coils})}
  function resize(){const r=stage.getBoundingClientRect();if(r.width<20||r.height<20)return;renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
  new ResizeObserver(resize).observe(stage);window.addEventListener('resize',resize);setTimeout(resize,50);
  let last=performance.now(),time=0,frames=[];const perf=document.querySelector('#core3dPerf');let visible=true;new IntersectionObserver(e=>visible=!!e[0]?.isIntersecting,{threshold:.03}).observe(stage);
  function animate(now){requestAnimationFrame(animate);if(!visible||!view.classList.contains('active-view')){last=now;return}const dt=Math.min(.05,(now-last)/1000);last=now;time+=dt;dyn.forEach(d=>{if(d.type==='spin')d.o.rotation.y+=dt*d.rate;else if(d.type==='float')d.o.position.y=d.baseY+Math.sin(time*d.rate)*d.amp;else if(d.type==='radial'){const a=time*d.rate;d.o.position.set(d.r*Math.cos(a),.25*Math.sin(a*2),d.r*Math.sin(a))}else if(d.type==='orbit'){const a=time*d.rate;d.o.position.set(d.r*Math.cos(a),0,d.r*Math.sin(a));d.o.rotation.y=-a;d.fg.position.copy(d.o.position);d.fg.setDirection(new THREE.Vector3(-Math.cos(a),0,-Math.sin(a)));d.vv.position.copy(d.o.position);d.vv.setDirection(new THREE.Vector3(-Math.sin(a),0,Math.cos(a)))}else if(d.type==='chargePulse'){d.arr.forEach((o,i)=>o.material.opacity=.35+.55*(.5+.5*Math.sin(time*d.rate+i*.55)))}else if(d.type==='dielectric'){d.o.material.opacity=.08+.3*d.frac*(.6+.4*Math.sin(time*.8))}else if(d.type==='rc'){const f=Math.exp(-((time*d.rate)%Math.max(.4,d.tau*2))/Math.max(.3,d.tau));d.arr.forEach((o,i)=>{o.position.x=-3+((time*d.rate+i/12*6)%6);o.material.opacity=.12+.8*f});d.cap.forEach(o=>o.material.emissive?.setScalar?.(0))}else if(d.type==='wire'){d.o.position.z=Math.sin(time*d.rate)*.12*Math.sign(d.I||1);d.arrow.setLength(1.2+.25*Math.sin(time*d.rate))}else if(d.type==='path'){const i=Math.floor((time*d.rate*48)%d.pts.length);d.o.position.copy(d.pts[(d.sign<0?(d.pts.length-i)%d.pts.length:i)])}else if(d.type==='wobble')d.o.rotation.z=d.base+Math.sin(time*d.rate)*d.amp;else if(d.type==='rotate')d.o.rotation.z=time*d.rate;else if(d.type==='wave'){const i=Math.floor((time*d.rate*60)%d.pts.length);d.o.position.copy(d.pts[i])}else if(d.type==='corePulse'){const u=(time*d.rate)%1;const perimeter=17.2,dist=u*perimeter;if(dist<6)d.o.position.set(-3+dist,2.15,0);else if(dist<10.3)d.o.position.set(3,2.15-(dist-6),0);else if(dist<16.3)d.o.position.set(3-(dist-10.3),-2.15,0);else d.o.position.set(-3,-2.15+(dist-16.3),0);d.coils.forEach((o,i)=>o.rotation.z+=dt*.08*Math.sin(time+i))}});renderer.render(scene,camera);frames.push(1/Math.max(.001,dt));if(frames.length>50)frames.shift();if(perf&&Math.floor(now/1000)%2===0){const avg=frames.reduce((a,b)=>a+b,0)/frames.length;perf.textContent=avg>48?'high-DPI · smooth':avg>30?'3D · balanced':'3D · performance'}}requestAnimationFrame(animate);
  const title=document.querySelector('#simTitle');new MutationObserver(()=>{setTimeout(()=>{build();resize()},20)}).observe(title,{childList:true,subtree:true});document.querySelector('#simControls')?.addEventListener('input',()=>requestAnimationFrame(build));document.querySelector('#resetSim')?.addEventListener('click',()=>setTimeout(build,20));
  build();resize();
}
