(()=>{'use strict';
const D=window.FIELD_LAB||{},$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const norm=s=>String(s||'').toLowerCase().replace(/[−–—]/g,'-').replace(/²/g,'2').replace(/³/g,'3').replace(/[×·]/g,'*').replace(/[^a-z0-9+\-/*=(). ]/g,' ').replace(/\s+/g,' ').trim();
const stop=new Set('the a an and or of to in on for from with that this is are was were be by as at it its into when where which use using explain describe state calculate determine find give show how why'.split(' '));
const toks=s=>norm(s).split(' ').filter(w=>w.length>2&&!stop.has(w));
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function pointHit(answer,point){const A=new Set(toks(answer)),P=[...new Set(toks(point))];if(!P.length)return false;let hit=P.filter(x=>A.has(x)).length;const phrase=norm(point);if(norm(answer).includes(phrase))return true;return hit/Math.min(P.length,7)>=.5;}
function mark(answer,points){const hits=points.filter(p=>pointHit(answer,p)),missing=points.filter(p=>!pointHit(answer,p));return{marks:hits.length,max:points.length,pct:points.length?Math.round(100*hits.length/points.length):0,hits,missing}}
window.FieldsAutoMarkV8={mark};

const bank=[
['Fields: the unifying idea','fields',6,'Explain how gravitational and electric fields provide a common model for non-contact interactions. Your answer should compare field strength, potential, field direction and the inverse-square behaviour of point sources.',['field strength is a vector','potential is a scalar','point-source field strength follows an inverse-square relationship','gravitational field direction is the force direction on a test mass','electric field direction is the force direction on a positive test charge','gravitational interaction is always attractive whereas electric interaction can attract or repel']],
["Newton's law and gravitational field strength",'gravity',6,'Starting from Newton’s law of gravitation, derive the expression for gravitational field strength around a spherical mass and explain what the equation tells you about distance and test mass.',['F = GMm/r2','g = F/m','g = GM/r2','test mass cancels','r is measured from the centre of the spherical mass','g follows an inverse-square relationship']],
['Gravitational potential and equipotentials','gravity',6,'Explain why gravitational potential is negative when zero is defined at infinity. Link your answer to work done, potential energy, equipotential surfaces and the V–r graph.',['zero potential is defined at infinity','gravitational potential is work or energy per unit mass','bound positions have negative potential','energy must be supplied to move a mass to infinity','no work is done moving along an equipotential','potential approaches zero from below as distance increases']],
['Circular orbits: speed, period and energy','gravity',6,'Derive the circular-orbit speed equation and use it to explain why a larger circular orbit has a lower speed but a longer period.',['gravity supplies the centripetal force','GMm/r2 = mv2/r','v = sqrt(GM/r)','orbital speed decreases as radius increases','T = 2*pi*r/v','T2 is proportional to r3 for a fixed central mass']],
['Escape velocity and synchronous satellites','gravity',6,'Use conservation of energy to explain escape speed, then state the additional conditions required for a geostationary satellite.',['minimum escape reaches infinity with zero final speed','initial kinetic energy supplies the increase in gravitational potential energy','v_escape = sqrt(2GM/R)','period equals Earth rotational period','orbit is equatorial and circular','satellite moves in the same direction as Earth rotation']],
["Coulomb's law",'electric',6,'Compare Coulomb’s law with Newton’s law of gravitation, including mathematical similarities, physical differences and the role of charge sign.',['both are inverse-square force laws','both act along the line joining the sources','gravity is always attractive','electric force can be attractive or repulsive','electric force depends on charge and permittivity','gravitational force depends on mass and G']],
['Electric field strength: uniform and radial','electric',6,'A charged particle enters a uniform electric field with velocity perpendicular to the field. Explain the motion and the assumptions that make the trajectory analogous to projectile motion.',['uniform field gives constant electric field strength','force qE is constant','acceleration in the field direction is constant','velocity perpendicular to the field remains constant','trajectory is parabolic in the ideal field region','charge sign determines acceleration direction']],
['Electric potential and equipotentials','electric',6,'Explain the distinction between electric potential, electric potential energy and electric field strength. Include what happens when a charge moves along an equipotential.',['electric potential is scalar energy or work per unit positive charge','potential energy is qV','electric field strength is vector force per unit positive charge','charge sign affects force and potential energy','potential difference along an equipotential is zero','no electric work is done along an equipotential']],
['Capacitance and parallel plates','capacitance',6,'Explain how plate area, plate separation and a dielectric affect the capacitance of a parallel-plate capacitor, including the microscopic role of polarisation.',['C = epsilon0 epsilonr A/d','increasing plate area increases capacitance','increasing separation decreases capacitance','a dielectric increases capacitance','polarisation reduces the effective internal field for a given free charge','more charge can be stored for the same potential difference']],
['Energy stored in a capacitor','capacitance',6,'Explain why the energy stored in a capacitor is 1/2 QV rather than QV. Use the charging process or the area under a suitable graph.',['potential difference rises from zero during charging','work for each small charge transfer depends on instantaneous potential difference','average potential difference is V/2 for ideal linear charging','energy = 1/2 QV','energy is the area under a V-Q or Q-V graph','the triangular area gives the factor one-half']],
['Capacitor charge/discharge and time constant','capacitance',6,'Describe capacitor discharge through a resistor and explain how Required Practical 9 can determine RC using a log-linear graph.',['voltage charge and current fall exponentially','time constant tau = RC','after one time constant the discharging quantity is about 1/e of its initial value','V = V0 exp(-t/RC)','ln(V/V0) = -t/RC','gradient of ln(V/V0) against time is -1/RC']],
['Magnetic flux density and force on a wire','magnetic',6,'Explain how Required Practical 10 can test F = BIL using a top-pan balance. Include controls, graph analysis and conversion of a balance reading into force.',['wire is perpendicular to a magnetic field','balance detects an equal and opposite force on the magnet system','mass change is converted using F = delta m g','vary one of B I or L while controlling the others','F against I is linear when B and L are constant','gradient of F against I equals BL']],
['Moving charges and circular paths','magnetic',6,'Explain why a charged particle moving perpendicular to a uniform magnetic field follows a circular path and derive the radius expression.',['magnetic force F = BQv','force is perpendicular to velocity','magnetic force supplies centripetal force','BQv = mv2/r','r = mv/(BQ)','reversing field direction or charge sign reverses the curvature direction']],
['Magnetic flux and flux linkage','magnetic',6,'Explain magnetic flux and flux linkage for a rotating coil, including the meaning of angle in NΦ = BANcosθ and how RP11 can test the relationship.',['flux depends on magnetic flux density and area normal to the field','flux linkage is N times flux','Nphi = BAN cos theta','theta is measured between the magnetic field and the coil normal','flux linkage is zero at 90 degrees','plotting Nphi against cos theta gives a straight line']],
['Faraday and Lenz laws / electromagnetic induction','magnetic',6,'A magnet is pushed into a coil and then pulled out. Explain the origin, magnitude and direction of the induced emf and current using Faraday’s and Lenz’s laws.',['motion changes magnetic flux linkage','induced emf depends on the rate of change of flux linkage','faster motion gives a larger magnitude of emf','Lenz law says the induced effect opposes the change producing it','reversing the motion reverses the direction of induced current','the induced magnetic field changes direction between entry and exit']],
['Rotating-coil generator','magnetic',6,'Explain why flux linkage and induced emf are a quarter cycle out of phase for a rotating coil generator.',['flux linkage varies as cosine of angular position','emf is the rate of change of flux linkage','emf is zero when flux linkage is at a maximum or minimum','emf is maximum when flux linkage passes through zero','emf varies sinusoidally','peak emf increases with BAN omega']],
['Alternating current, rms and oscilloscope','magnetic',6,'Explain the meaning of rms voltage and how an oscilloscope trace can be used to determine peak voltage, rms voltage, period and frequency.',['rms voltage gives the equivalent dc heating effect','for a sinusoid Vrms = Vpeak/sqrt2','vertical scale gives peak voltage','horizontal timebase gives period','frequency f = 1/T','measurements should use divisions multiplied by the oscilloscope scales']],
['Transformers and transmission','magnetic',6,'Explain how a transformer changes voltage and why electrical energy is transmitted at high voltage. Include turns ratio, power, current and I2R losses.',['Vs/Vp = Ns/Np','transformer requires changing magnetic flux and therefore alternating current','for approximately conserved power P = VI','higher transmission voltage gives lower current for the same power','line loss is I2R','reducing current greatly reduces heating loss']]
].map(([lesson,topic,marks,q,pts])=>({lesson,topic,marks,q,pts}));

function currentLesson(){const t=$('#lessonPanel h2')?.textContent?.trim();return (D.lessons||[]).find(x=>x.title===t)}
function feedbackHTML(r){const cls=r.pct>=75?'good':r.pct>=45?'mid':'low';return `<div class="auto-feedback-v8 ${cls}"><strong>${r.marks} / ${r.max} indicative mark points</strong><p>${r.hits.length?'Detected: '+r.hits.map(esc).join(' · '):'No clear mark points detected yet.'}</p>${r.missing.length?`<p><strong>To improve:</strong> ${r.missing.slice(0,4).map(esc).join(' · ')}</p>`:'<p>All indicative points detected.</p>'}<small>Practice automarking is indicative and rewards physics ideas rather than exact wording.</small></div>`}
function expectedForTextarea(ta,l){const q=ta.closest('.mini-question');if(q){const ans=q.querySelector('.answer-reveal')?.textContent?.trim();if(ans)return [ans]}
 const calc=ta.closest('.calc-practice');if(calc){const ans=calc.querySelector('.calc-final')?.textContent?.trim();if(ans)return [ans,'SI units','valid conditions']}
 if(ta.closest('[data-chunk="7"]'))return [l.activity,...(l.keywords||[]).slice(0,5),...(l.objectives||[]).slice(0,2)];
 if(ta.closest('[data-chunk="11"]'))return [l.exit,...(l.keywords||[]).slice(0,5),l.examTip];
 return [...(l.keywords||[]).slice(0,6),...(l.objectives||[]).slice(0,2)];}
function wireLessonAutoMark(){const p=$('#lessonPanel'),l=currentLesson();if(!p||!l)return;$$('textarea',p).forEach(ta=>{if(ta.dataset.v8Mark)return;ta.dataset.v8Mark='1';const old=ta.nextElementSibling?.classList?.contains('auto-v6')?ta.nextElementSibling:null;const host=old||document.createElement('div');host.className='auto-v8';host.innerHTML='<button type="button" class="button primary">Auto-mark answer</button><div class="v8-feedback"></div>';if(!old)ta.insertAdjacentElement('afterend',host);const pts=expectedForTextarea(ta,l);$('button',host).onclick=()=>{$('.v8-feedback',host).innerHTML=ta.value.trim()?feedbackHTML(mark(ta.value,pts)):'<div class="auto-feedback-v8 low">Write an answer first.</div>'}});
 const mcq=$$('[data-answer]',p);mcq.forEach(b=>{if(b.dataset.v8Mcq)return;b.dataset.v8Mcq='1';b.addEventListener('click',()=>setTimeout(()=>{const result=$('#checkResult',p);if(result&&!result.querySelector('.v8-mcq-note'))result.insertAdjacentHTML('afterbegin','<div class="v8-mcq-note">Automatically checked ✓</div>')},0))});
 addLessonExtended(p,l);
}
function addLessonExtended(p,l){if(p.querySelector('.lesson-extended-v8'))return;const item=bank.find(x=>x.lesson===l.title)||bank.find(x=>x.topic===l.topic);if(!item)return;const sec=document.createElement('section');sec.className='lesson-extended-v8';sec.innerHTML=`<span class="eyebrow">Extended response practice · ${item.marks} marks</span><h3>Finish the lesson with sustained reasoning</h3><p><strong>${esc(item.q)}</strong></p><div class="v8-plan-grid"><label><span>Physics points</span><textarea placeholder="List the physics ideas you need..."></textarea></label><label><span>Equation / graph</span><textarea placeholder="Which equation, derivation or graph relationship will you use?"></textarea></label><label><span>Conclusion</span><textarea placeholder="What conclusion will directly answer the question?"></textarea></label></div><textarea class="student-answer v8-extended-answer" placeholder="Write your full extended response here..."></textarea><div class="button-row"><button class="button primary v8-mark-extended">Auto-mark extended response</button><button class="button v8-show-points">Show indicative mark points</button></div><div class="v8-extended-feedback"></div><div class="v8-points hidden"><ul>${item.pts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;p.querySelector('.lesson-actions')?.before(sec);sec.querySelector('.v8-mark-extended').onclick=()=>{const a=sec.querySelector('.v8-extended-answer').value;sec.querySelector('.v8-extended-feedback').innerHTML=a.trim()?feedbackHTML(mark(a,item.pts)):'<div class="auto-feedback-v8 low">Write your extended response first.</div>'};sec.querySelector('.v8-show-points').onclick=()=>sec.querySelector('.v8-points').classList.toggle('hidden')}

function buildExtendedHub(){const root=$('#extendedResponseApp');if(!root||root.querySelector('.extended-v8-hub'))return;const hub=document.createElement('section');hub.className='extended-v8-hub';hub.innerHTML=`<div class="section-head compact"><div><span class="eyebrow">v8 · automarked practice</span><h2>Extended Response Practice Centre</h2></div><p class="muted">One substantial response for every lesson area. Plan, write, automark against indicative physics points, then improve.</p></div><div class="topic-filter v8-topic-filter"><button class="button primary" data-v8-topic="all">All topics</button><button class="button" data-v8-topic="gravity">Gravity</button><button class="button" data-v8-topic="electric">Electric</button><button class="button" data-v8-topic="capacitance">Capacitance</button><button class="button" data-v8-topic="magnetic">Magnetic</button></div><div class="v8-er-list"></div>`;root.prepend(hub);let filter='all';const render=()=>{const list=hub.querySelector('.v8-er-list');list.innerHTML='';bank.filter(x=>filter==='all'||x.topic===filter).forEach(item=>{const card=document.createElement('article');card.className='panel pad v8-er-card';card.innerHTML=`<div class="lesson-meta"><span class="eyebrow">${esc(item.lesson)}</span><span class="data-badge">${item.marks} marks</span></div><h3>${esc(item.q)}</h3><textarea class="student-answer" placeholder="Write a complete A-level response..."></textarea><div class="button-row"><button class="button primary">Auto-mark</button><button class="button">Mark points</button></div><div class="v8-f"></div><div class="v8-p hidden"><ul>${item.pts.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`;const buttons=card.querySelectorAll('button');buttons[0].onclick=()=>{const a=card.querySelector('textarea').value;card.querySelector('.v8-f').innerHTML=a.trim()?feedbackHTML(mark(a,item.pts)):'<div class="auto-feedback-v8 low">Write an answer first.</div>'};buttons[1].onclick=()=>card.querySelector('.v8-p').classList.toggle('hidden');list.appendChild(card)})};hub.querySelectorAll('[data-v8-topic]').forEach(b=>b.onclick=()=>{filter=b.dataset.v8Topic;hub.querySelectorAll('[data-v8-topic]').forEach(x=>x.classList.toggle('primary',x===b));render()});render()}

function sharpResizeTriggers(){document.addEventListener('click',e=>{const b=e.target.closest('[data-view],[data-jump]');const v=b?.dataset.view||b?.dataset.jump;if(v==='lab'||v==='advanced')setTimeout(()=>window.dispatchEvent(new Event('resize')),40)});const adv=$('#view-advanced'),lab=$('#view-lab');if('ResizeObserver'in window){[adv,lab].filter(Boolean).forEach(el=>new ResizeObserver(()=>{if(el.classList.contains('active-view'))window.dispatchEvent(new Event('resize'))}).observe(el))}}

const obs=new MutationObserver(()=>{wireLessonAutoMark();buildExtendedHub()});const panel=$('#lessonPanel');if(panel)obs.observe(panel,{childList:true});
wireLessonAutoMark();buildExtendedHub();sharpResizeTriggers();
})();
