(() => {
'use strict';
const D=window.FIELD_LAB||{};
const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));

const topicData={
 fields:{compare:'Gravitational and electrostatic fields can both be represented with field lines, potentials and equipotentials, but mass has one sign while electric charge may be positive or negative.',math:'For point sources, force and field strength follow inverse-square behaviour. Potential follows an inverse-distance relationship.',graph:'Compare the different curvature of a 1/r² field graph with a 1/r potential graph.',practical:'Use probe readings from several positions, identify the independent variable, then decide whether the pattern is consistent with an inverse-square law.'},
 gravity:{compare:'Use one consistent chain: Newtonian gravitation → field strength → potential → circular motion → orbital energy.',math:'Be fluent moving between F = GMm/r², g = GM/r², V = −GM/r, v = √(GM/r), T² = 4π²r³/(GM) and orbital energy.',graph:'Use g–r and V–r graphs to connect field strength, potential difference, gradients and areas.',practical:'Treat orbital data like experimental data: transform variables where useful, plot an appropriate graph and use the gradient to infer a physical constant or source mass.'},
 electric:{compare:'Field strength is vector; electric potential is scalar. The sign of the source charge affects potential and field direction, while the sign of a test charge affects force direction.',math:'Link Coulomb force to E = F/q and then to radial E = kQ/r². In a uniform field use E = V/d and ΔE = qΔV.',graph:'Recognise radial E–r and V–r shapes and distinguish them from the constant field between parallel plates.',practical:'A field-mapping investigation can test symmetry, identify equipotential lines and compare measured gradients with field direction.'},
 capacitance:{compare:'Separate three ideas: capacitance describes construction, stored energy depends on Q/V state, and charge/discharge dynamics depend on RC.',math:'Use C = Q/V, C = ε₀εrA/d, E = ½QV = ½CV² = Q²/(2C), τ = RC, and the exponential charging/discharging equations.',graph:'Connect Q–V area with stored energy, exponential time graphs with τ, and log-linear plots with gradient −1/RC.',practical:'RP9 should be treated as a complete analysis exercise: apparatus choice, control variables, repeated readings, uncertainty, log transformation, best-fit line and interpretation of gradient.'},
 magnetic:{compare:'Magnetism links force, circular motion, geometry and induction. Always identify the direction of B, current/velocity and force before calculating.',math:'Use F = BIL, F = BQv, r = mv/(BQ), Φ = BA, NΦ = BANcosθ and ε = Δ(NΦ)/Δt.',graph:'Connect flux-linkage graphs to induced-emf graphs through rate of change; interpret AC traces using peak, rms, period and frequency.',practical:'RP10 and RP11 should include apparatus setup, controlled variables, uncertainty, graph gradient and a conclusion tied directly to the governing equation.'}
};

function specific(title){const t=title.toLowerCase();
 if(t.includes('fields:')) return {why:'A field is a model that allows force effects to be described at every point in space without requiring direct contact.',extension:'Explain why two points can have the same electric potential but different electric-field vectors, and why equipotentials are perpendicular to field lines.',calc:'If a point-source field is 72 units at r, predict and then calculate its value at 3r.'};
 if(t.includes("newton's")||t.includes('gravitational field strength')) return {why:'Dividing Newton’s gravitational force by test mass gives a property of the source field, g, independent of the chosen test mass.',extension:'Use dimensional analysis to show that GM/r² has units equivalent to N kg⁻¹ and m s⁻².',calc:'Compare surface g on two planets when one has twice the mass and 1.5 times the radius.'};
 if(t.includes('gravitational potential')) return {why:'Potential is energy per unit mass; the negative sign follows from choosing zero at infinity and recognising that bound states lie below that reference.',extension:'Explain how the area under a g–r graph between two radii relates to gravitational potential difference.',calc:'Calculate ΔEp for a satellite moving between two quoted gravitational potentials.'};
 if(t.includes('circular orbit')) return {why:'A stable circular orbit occurs when gravity supplies exactly the inward acceleration required by the tangential speed.',extension:'Derive T² ∝ r³ and explain how a T² against r³ plot can be used to estimate the central mass.',calc:'Predict the factor change in orbital speed and period if orbital radius is quadrupled.'};
 if(t.includes('escape')||t.includes('synchronous')) return {why:'Escape speed is an energy threshold, whereas geostationary motion is a particular circular orbit satisfying both period and geometry conditions.',extension:'Compare synchronous and geostationary orbits and explain why every geostationary orbit is synchronous but not every synchronous orbit is geostationary.',calc:'Show that escape speed is √2 times circular orbital speed at the same radius.'};
 if(t.includes('coulomb')) return {why:'Coulomb’s law has the same inverse-square mathematical form as gravitation, but charge can have either sign.',extension:'Compare the gravitational and electrostatic force between a proton and electron and explain why the enormous ratio matters for atomic structure.',calc:'Calculate the change in electrostatic force if one charge triples and separation doubles.'};
 if(t.includes('electric field strength')) return {why:'E is force per unit positive charge, so it describes the field independent of the test charge used to measure it.',extension:'Use energy reasoning to derive E = V/d for a uniform field between parallel plates.',calc:'A particle crosses a uniform field at right angles; explain the analogy with projectile motion.'};
 if(t.includes('electric potential')) return {why:'Electric potential is scalar, making superposition different from electric field strength.',extension:'Construct a situation where V = 0 but E ≠ 0 and explain why this does not contradict the definitions.',calc:'Calculate electric potential energy change for an electron moving through a specified pd.'};
 if(t.includes('parallel plate')||t.includes('dielectric')||t==='capacitance') return {why:'Capacitance depends on geometry and dielectric response, not on how much charge happens to be stored at one moment.',extension:'Explain microscopically how polarisation of a dielectric reduces the effective field and increases capacitance.',calc:'Find the factor change in C when area doubles, separation halves and εr increases by 1.5.'};
 if(t.includes('energy stored')) return {why:'The factor ½ appears because pd rises from zero while charge is transferred; the average pd during an ideal charging process is V/2.',extension:'Use the area under a Q–V graph to justify E = ½QV and connect this to the other energy forms.',calc:'Compare stored energy when pd doubles for a fixed capacitor.'};
 if(t.includes('charge')||t.includes('discharge')||t.includes('time constant')) return {why:'The current falls as the capacitor pd changes, creating an exponential process controlled by the product RC.',extension:'Derive the straight-line log form and explain why a best-fit gradient is preferable to estimating τ from one point.',calc:'Use a measured gradient of ln(V/V₀) against t to determine C when R is known.'};
 if(t.includes('flux density')||t.includes('wire')) return {why:'The force on a current-carrying conductor is the macroscopic result of magnetic forces on moving charge carriers.',extension:'Explain why an RP10 graph of F against I should pass through the origin and what a non-zero intercept could indicate experimentally.',calc:'Use the gradient of an F–I graph and known L to determine B.'};
 if(t.includes('moving charges')||t.includes('cyclotron')) return {why:'A magnetic force perpendicular to velocity changes direction but not speed, making circular motion possible.',extension:'Explain why a particle entering at an angle to B follows a helical path rather than a simple circle.',calc:'Compare proton and electron radii for equal speed and equal |q| in the same B.'};
 if(t.includes('flux linkage')||t.includes('magnetic flux')) return {why:'Flux is determined by the component of B normal to the area, which produces the cosine dependence.',extension:'Explain how an NΦ against cosθ graph can determine B and how uncertainty in angle affects the result near 90°.',calc:'Calculate flux linkage at 0°, 60° and 90° for the same coil.'};
 if(t.includes('faraday')||t.includes('induction')||t.includes('motional')) return {why:'Induced emf is controlled by how quickly flux linkage changes, not simply by how large the flux is.',extension:'Use energy conservation to explain the direction described by Lenz’s law when a magnet approaches a conducting coil.',calc:'Compare induced emf when turns double and the flux-change time halves.'};
 if(t.includes('rotating coil')||t.includes('generator')) return {why:'Uniform rotation makes flux linkage vary as cosine while induced emf varies as its rate of change.',extension:'Explain the quarter-cycle phase difference between flux linkage and emf using gradients rather than memorised graph positions.',calc:'Calculate peak emf and rms emf for a rotating coil from B, A, N and f.'};
 if(t.includes('alternating')||t.includes('rms')||t.includes('oscilloscope')) return {why:'RMS values are defined by equivalent heating/power effects, not by a simple arithmetic average of a sine wave.',extension:'Use an oscilloscope trace to determine Vpeak, Vpp, Vrms, period and frequency, including uncertainty from scale reading.',calc:'Find mains Vpeak and Vpp from a quoted Vrms.'};
 if(t.includes('transformer')) return {why:'A transformer transfers energy through changing core flux; stepping voltage up does not create energy because current changes correspondingly.',extension:'Explain copper losses, eddy-current losses and how design choices reduce them, then connect high transmission voltage to I²R losses.',calc:'Compare line losses before and after a tenfold increase in transmission voltage for fixed power.'};
 return {why:'Build a chain from physical model to equation to graph to evidence.',extension:'Explain how a change in one variable would affect the outcome and justify it using both words and equations.',calc:'Create a numerical example and check the scale and units of the result.'};
}

function add(){const p=$('#lessonPanel');if(!p||p.querySelector('.textbook-v4'))return;const title=p.querySelector('h2')?.textContent?.trim();if(!title)return;const l=(D.lessons||[]).find(x=>x.title===title);if(!l)return;const chunk=p.querySelector('.chunk[data-chunk="2"]');if(!chunk)return;const td=topicData[l.topic]||topicData.fields,s= specific(title);const sec=document.createElement('section');sec.className='textbook-v4';sec.innerHTML=`<div class="textbook-depth-head"><span class="eyebrow">A* textbook extension</span><h3>Go beyond recall: ${esc(title)}</h3><p>Use this section for deeper derivation, synoptic links, data analysis and longer-response preparation.</p></div><div class="textbook-v4-grid"><article class="tb-v4-card"><h4>Why the physics works</h4><p>${esc(s.why)}</p><div class="tb-v4-callout">${esc(td.compare)}</div></article><article class="tb-v4-card"><h4>Mathematical reasoning</h4><p>${esc(td.math)}</p><div class="tb-v4-equation">${(l.formulas||[]).map(esc).join('  •  ')}</div><p><strong>Calculation challenge:</strong> ${esc(s.calc)}</p></article><article class="tb-v4-card"><h4>Graphs and data</h4><p>${esc(td.graph)}</p><ul><li>State the expected shape before seeing data.</li><li>Identify what the gradient or area represents.</li><li>Comment on intercepts and whether the model predicts the graph should pass through the origin.</li><li>Use uncertainty and scatter to judge whether evidence supports the model.</li></ul></article><article class="tb-v4-card"><h4>Practical and Paper 3 thinking</h4><p>${esc(td.practical)}</p><ul><li>Independent, dependent and control variables.</li><li>Suitable range, repeats and resolution.</li><li>Random vs systematic uncertainty.</li><li>Graph choice and conclusion tied to physics.</li></ul></article><article class="tb-v4-card"><h4>Extended-response training</h4><p>${esc(s.extension)}</p><div class="tb-v4-callout tb-v4-a-star"><strong>A* structure:</strong> make a claim → give the governing physics → use an equation/graph → apply it to the situation → finish with a precise conclusion.</div></article><article class="tb-v4-card"><h4>What changes if…?</h4><ul><li>Double one variable while holding the others fixed.</li><li>Reverse a vector direction or sign where relevant.</li><li>Consider a limiting case such as r → ∞, θ → 90° or t ≫ RC.</li><li>Explain whether the result changes linearly, inversely, as an inverse square, exponentially or sinusoidally.</li></ul></article></div>`;chunk.appendChild(sec);}
const panel=$('#lessonPanel');if(panel){new MutationObserver(()=>requestAnimationFrame(add)).observe(panel,{childList:true});requestAnimationFrame(add);}
})();