import * as THREE from 'https://esm.sh/three@0.180.0';

const root=document.querySelector('#advancedApp');
if(!root||document.querySelector('#threeLabV9')){
  // no-op
}else{
  document.querySelector('#threeLabV8')?.remove();
  const section=document.createElement('section');
  section.id='threeLabV9';section.className='panel pad three-lab-v9';
  section.innerHTML=`<div class="three-v9-head"><div><span class="eyebrow">v9 · WebGL 3D · animated</span><h2>Animated 3D Physics Studio</h2><p class="muted">Every model now has continuous physics motion while visible. Drag to rotate the camera, scroll/pinch to zoom, and change the live experiment controls.</p></div><span class="sim-runtime-v9-badge">adaptive smooth rendering</span></div><div class="three-v9-tabs" id="threeV9Tabs"></div><div class="three-v9-layout"><div class="three-v9-stage-wrap"><div id="threeV9Stage" class="three-v9-stage" aria-label="Animated interactive 3D physics simulation"></div><div class="three-v9-overlay"><span class="pill" id="threeV9State">Playing</span><span class="pill" id="threeV9Fps">60 fps target</span></div><div class="three-v9-help">Drag = orbit camera · wheel/pinch = zoom · Play/Pause controls experiment motion</div></div><aside class="three-v9-side"><article class="three-v9-card"><span class="eyebrow">Current experiment</span><h3 id="threeV9Title"></h3><p class="muted" id="threeV9Desc"></p></article><div id="threeV9Controls" class="control-stack"></div><article class="three-v9-card"><span class="eyebrow">Animation controls</span><div class="three-v9-toolbar"><button class="button primary" id="threeV9Play">Pause</button><button class="button" id="threeV9Reset">Reset experiment</button><button class="button" id="threeV9Camera">Reset camera</button><button class="button primary" id="threeV9Vectors">Vectors on</button></div></article><article class="three-v9-card"><span class="eyebrow">Live physics</span><div id="threeV9Readout" class="three-v9-readout"></div></article></aside></div>`;
  root.prepend(section);
  const stage=section.querySelector('#threeV9Stage'),tabs=section.querySelector('#threeV9Tabs'),controlsHost=section.querySelector('#threeV9Controls'),readout=section.querySelector('#threeV9Readout'),titleEl=section.querySelector('#threeV9Title'),descEl=section.querySelector('#threeV9Desc'),fpsEl=section.querySelector('#threeV9Fps'),stateEl=section.querySelector('#threeV9State');
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});
  renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;stage.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x06111d);scene.fog=new THREE.Fog(0x06111d,20,58);
  const camera=new THREE.PerspectiveCamera(42,1,.1,120);let yaw=-.58,pitch=.34,distance=15;
  function updateCamera(){const cp=Math.cos(pitch),sp=Math.sin(pitch),cy=Math.cos(yaw),sy=Math.sin(yaw);camera.position.set(distance*cp*sy,distance*sp+1.1,distance*cp*cy);camera.lookAt(0,0,0)}updateCamera();
  scene.add(new THREE.HemisphereLight(0xc8ecff,0x172234,1.65));const key=new THREE.DirectionalLight(0xffffff,2.7);key.position.set(7,10,8);key.castShadow=true;key.shadow.mapSize.set(1536,1536);scene.add(key);const rim=new THREE.DirectionalLight(0x6bbfff,1.25);rim.position.set(-8,5,-7);scene.add(rim);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(42,42),new THREE.MeshStandardMaterial({color:0x0a1725,roughness:.94,metalness:.03}));floor.rotation.x=-Math.PI/2;floor.position.y=-2.8;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(42,42,0x234761,0x13293b);grid.position.y=-2.78;grid.material.transparent=true;grid.material.opacity=.28;scene.add(grid);
  const modelRoot=new THREE.Group();scene.add(modelRoot);
  const mat=(c,rough=.42,metal=.25,extra={})=>new THREE.MeshStandardMaterial({color:c,roughness:rough,metalness:metal,...extra});
  const glow=(c,em=.4)=>new THREE.MeshStandardMaterial({color:c,roughness:.3,metalness:.2,emissive:c,emissiveIntensity:em});
  const box=(w,h,d,m,x=0,y=0,z=0)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;modelRoot.add(o);return o};
  const sphere=(r,m,x=0,y=0,z=0,seg=32)=>{const o=new THREE.Mesh(new THREE.SphereGeometry(r,seg,Math.max(18,seg/2)),m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;modelRoot.add(o);return o};
  const cyl=(r,h,m,x=0,y=0,z=0,axis='y')=>{const o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,30),m);o.position.set(x,y,z);if(axis==='x')o.rotation.z=Math.PI/2;if(axis==='z')o.rotation.x=Math.PI/2;o.castShadow=o.receiveShadow=true;modelRoot.add(o);return o};
  const torus=(r,t,m,x=0,y=0,z=0,rotX=Math.PI/2)=>{const o=new THREE.Mesh(new THREE.TorusGeometry(r,t,16,54),m);o.position.set(x,y,z);o.rotation.x=rotX;o.castShadow=true;modelRoot.add(o);return o};
  const arrow=(dir,origin,len,color)=>{const a=new THREE.ArrowHelper(dir.clone().normalize(),origin,len,color,.32,.16);modelRoot.add(a);return a};
  function line(points,color=0x6fcaff){const g=new THREE.BufferGeometry().setFromPoints(points);const l=new THREE.Line(g,new THREE.LineBasicMaterial({color,transparent:true,opacity:.8}));modelRoot.add(l);return l}
  function dispose(o){o.traverse?.(x=>{x.geometry?.dispose?.();if(Array.isArray(x.material))x.material.forEach(m=>m.dispose?.());else x.material?.dispose?.()})}
  function clearModel(){for(const c of [...modelRoot.children]){dispose(c);modelRoot.remove(c)}anim=[];modelState={};elapsed=0}

  let dragging=false,lastX=0,lastY=0,pinchDist=0;
  renderer.domElement.addEventListener('pointerdown',e=>{dragging=true;lastX=e.clientX;lastY=e.clientY;renderer.domElement.setPointerCapture?.(e.pointerId)});
  renderer.domElement.addEventListener('pointermove',e=>{if(!dragging)return;const dx=e.clientX-lastX,dy=e.clientY-lastY;lastX=e.clientX;lastY=e.clientY;yaw-=dx*.006;pitch=Math.max(-.15,Math.min(1.16,pitch-dy*.005));updateCamera()});
  renderer.domElement.addEventListener('pointerup',()=>dragging=false);renderer.domElement.addEventListener('pointercancel',()=>dragging=false);
  renderer.domElement.addEventListener('wheel',e=>{e.preventDefault();distance=Math.max(7,Math.min(28,distance+e.deltaY*.012));updateCamera()},{passive:false});
  renderer.domElement.addEventListener('touchstart',e=>{if(e.touches?.length===2){pinchDist=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY)}},{passive:true});
  renderer.domElement.addEventListener('touchmove',e=>{if(e.touches?.length===2&&pinchDist){const d=Math.hypot(e.touches[0].clientX-e.touches[1].clientX,e.touches[0].clientY-e.touches[1].clientY);distance=Math.max(7,Math.min(28,distance+(pinchDist-d)*.02));pinchDist=d;updateCamera()}},{passive:true});

  const G=6.67430e-11,e=1.602176634e-19;
  const defs={
    orbit:{name:'Orbit & gravitational field',desc:'Animated 3D circular orbit with live velocity and gravitational-force vectors.',controls:[['mass','Planet mass / 10²⁴ kg',1,9,.1,5.97],['radius','Orbit radius / 10⁶ m',7,35,.5,12],['speed','Speed / circular speed',.55,1.35,.01,1]]},
    electric:{name:'Electric field & charged-particle trajectory',desc:'Parallel plates with animated field markers and a charged particle following a projectile-like path.',controls:[['voltage','Plate pd / V',100,2500,25,900],['gap','Plate separation / cm',2,12,.5,6],['charge','Particle charge / e',-3,3,1,1],['launch','Launch speed / relative',.5,2,.05,1]]},
    capacitor:{name:'Capacitor charge/discharge (RP9)',desc:'Animated plate charge, electron/current flow and dielectric insertion with a live RC time scale.',controls:[['mode','Process','select',[['charge','Charge'],['discharge','Discharge']],'charge'],['voltage','Supply / V',1,12,.2,6],['R','Resistance / kΩ',1,15,.5,4.7],['C','Capacitance / µF',100,1000,10,470],['gap','Plate gap / relative',.7,1.8,.05,1],['dielectric','Dielectric fraction',0,1,.05,0]]},
    magnetic:{name:'Magnetic force & particle chamber',desc:'Animated current flow, force vector and charged-particle circular motion in a 3D magnetic field.',controls:[['B','Flux density / T',.05,.8,.01,.3],['I','Wire current / A',-5,5,.1,2],['speed','Particle speed / 10⁶ m s⁻¹',.5,5,.1,2],['charge','Particle sign','select',[['positive','Positive'],['negative','Negative']],'positive']]},
    induction:{name:'Electromagnetic induction',desc:'A moving magnet continuously changes coil flux linkage; coil glow shows induced-emf magnitude and direction.',controls:[['speed','Magnet motion speed',.2,3,.1,1],['turns','Coil turns',40,400,20,180],['strength','Magnet strength',.4,1.8,.1,1]]},
    transformer:{name:'Transformer & transmission',desc:'Animated AC excitation, magnetic-flux pulses in the iron core and secondary/load response.',controls:[['Np','Primary turns',100,900,50,400],['Ns','Secondary turns',100,2400,50,1200],['Vp','Primary voltage / V',12,500,1,230],['power','Transferred power / W',200,5000,100,1500],['lineR','Line resistance / Ω',.5,12,.5,3]]},
    wire:{name:'Force-on-wire balance (RP10)',desc:'Animated conventional-current markers through a wire in a magnetic field with a live force vector and balance response.',controls:[['B','Flux density / T',.05,.7,.01,.25],['I','Current / A',-6,6,.1,2],['L','Length in field / m',.02,.15,.005,.08]]},
    coil:{name:'Search coil & oscilloscope (RP11)',desc:'A rotating search coil continuously changes flux linkage and induced emf in a realistic magnet gap.',controls:[['B','Flux density / T',.02,.3,.01,.1],['N','Turns',50,500,10,200],['area','Coil area / cm²',10,100,5,50],['angle','Start angle / °',0,180,1,30],['sweep','Rotation speed / ° s⁻¹',0,120,5,45]]}
  };
  let mode='orbit',values={},playing=true,vectors=true,elapsed=0,last=performance.now(),anim=[],modelState={},visible=true,lastRead=0,qualityPixel=Math.min(window.devicePixelRatio||1,2),fps=[];
  const defaults=()=>{const o={};defs[mode].controls.forEach(c=>o[c[0]]=c[2]==='select'?c[4]:c[5]);return o};
  const fmt=n=>!Number.isFinite(n)?'—':((Math.abs(n)>0&&(Math.abs(n)<1e-3||Math.abs(n)>=1e5))?n.toExponential(3):Number(n.toFixed(Math.abs(n)<10?3:2)).toString());
  function setReadout(items){readout.innerHTML=items.map((x,i)=>i===0?`<strong>${x}</strong>`:`<span>${x}</span>`).join('')}
  function buildOrbit(){const M=values.mass*1e24,r=values.radius*1e6,vc=Math.sqrt(G*M/r),v=vc*values.speed,vesc=Math.sqrt(2*G*M/r),T=2*Math.PI*Math.sqrt(r**3/(G*M)),orbitR=3.2+(values.radius-7)/28*3.2;const planet=sphere(2.05,mat(0x2f77b7,.72,.03));sphere(2.12,new THREE.MeshPhysicalMaterial({color:0x68cfff,transparent:true,opacity:.11,roughness:.15,transmission:.2}));torus(orbitR,.018,new THREE.MeshBasicMaterial({color:0x5fbde8,transparent:true,opacity:.6}));const sat=new THREE.Group();const body=new THREE.Mesh(new THREE.BoxGeometry(.5,.3,.72),mat(0xd8e4ef,.22,.8));body.castShadow=true;sat.add(body);for(const z of[-.65,.65]){const p=new THREE.Mesh(new THREE.BoxGeometry(.85,.035,.38),mat(0x244d82,.45,.12));p.position.z=z;sat.add(p)}modelRoot.add(sat);const f=arrow(new THREE.Vector3(-1,0,0),new THREE.Vector3(orbitR,0,0),1.35,0x78e6a1),vv=arrow(new THREE.Vector3(0,0,1),new THREE.Vector3(orbitR,0,0),1.55,0xf2c86b);modelState={planet,sat,f,vv,orbitR,speedFactor:values.speed};setReadout([`v = ${fmt(v)} m s⁻¹`,`circular ${fmt(vc)} m s⁻¹ · escape ${fmt(vesc)} m s⁻¹`,`period ${fmt(T)} s`])}
  function buildElectric(){const gap=1.15+values.gap*.13,E=values.voltage/(values.gap/100),q=values.charge*e,F=q*E;box(.2,5.2,6,mat(0xbcc7d3,.22,.88),-gap,0,0);box(.2,5.2,6,mat(0x8f9dad,.22,.88),gap,0,0);for(let y=-2;y<=2;y+=.85)for(let z=-2.4;z<=2.4;z+=.9){sphere(.055,glow(0xe46161,.25),-gap+.13,y,z,18);sphere(.055,glow(0x5d86df,.25),gap-.13,y,z,18)}const markers=[];for(let y=-1.8;y<=1.8;y+=.9)for(let z=-1.8;z<=1.8;z+=1.2){const s=sphere(.055,glow(0x72d9ff,.75),-gap+.3,y,z,16);markers.push({s,off:Math.random()})}const particle=sphere(.23,glow(values.charge>=0?0xf06a6a:0x6b91ef,.5),0,0,-2.8);const pathPts=[];const sign=Math.sign(values.charge||1);for(let i=0;i<=80;i++){const u=i/80;pathPts.push(new THREE.Vector3(sign*.9*u*u,0,-2.8+5.6*u))}line(pathPts,0xc7a8ff);modelState={gap,markers,particle,sign,launch:values.launch};setReadout([`E = ${fmt(E)} V m⁻¹`,`F on particle = ${fmt(F)} N`,`positive charge accelerates with E; negative charge opposite E`])}
  function buildCapacitor(){const gap=1.15*values.gap,area=2.9,plateMat=mat(0xb8c6d5,.18,.9);box(.16,area,area,plateMat,-gap/2,0,0);box(.16,area,area,plateMat,gap/2,0,0);if(values.dielectric>0)box(Math.max(.05,gap*.9*values.dielectric),area*.91,area*.91,new THREE.MeshPhysicalMaterial({color:0x77c9d9,transparent:true,opacity:.32,roughness:.2,transmission:.45}),0,0,0);const plus=[],minus=[];for(let y=-1.1;y<=1.1;y+=.55)for(let z=-1.1;z<=1.1;z+=.55){plus.push(sphere(.055,glow(0xe55c5c,.35),-gap/2+.13,y,z,16));minus.push(sphere(.055,glow(0x5f87df,.35),gap/2-.13,y,z,16))}const wireMat=mat(0xd47a35,.22,.86);cyl(.055,3.1,wireMat,0,2.1,-1.8,'x');cyl(.055,3.1,wireMat,0,-2.1,-1.8,'x');const beads=[];for(let i=0;i<12;i++)beads.push(sphere(.07,glow(0x74dfff,.7),-1.5+i*.28,2.1,-1.8,16));const tau=values.R*1e3*values.C*1e-6;modelState={plus,minus,beads,tau,mode:values.mode,V0:values.voltage};setReadout([`τ = ${fmt(tau)} s`,`C setting ${values.C.toFixed(0)} µF · R ${values.R.toFixed(1)} kΩ`,`dielectric insertion ${Math.round(values.dielectric*100)}%`])}
  function buildMagnetic(){box(2.1,2.3,4.8,mat(0xbd4d4d,.42,.08),-3,1.5,0);box(2.1,2.3,4.8,mat(0x4d73bd,.42,.08),-3,-1.5,0);for(let x=-1.6;x<=2.2;x+=.95)for(let z=-1.6;z<=1.6;z+=1.1)arrow(new THREE.Vector3(0,-1,0),new THREE.Vector3(x,1.1,z),2.15,0x68cfff);cyl(.09,5.3,mat(0xd47a35,.22,.86),.15,0,0,'x');const beads=[];for(let i=0;i<10;i++)beads.push(sphere(.065,glow(0xf2c86b,.65),-2.4+i*.5,.18,0,16));const chargeSign=values.charge==='negative'?-1:1,radius=Math.max(1.1,Math.min(4.1,2.7*(values.speed/2)/(values.B/.3)));const curve=new THREE.EllipseCurve(0,0,radius,radius,0,Math.PI*1.75,false,0),pts=curve.getPoints(120).map(p=>new THREE.Vector3(p.x+3.1,p.y-1.2,p.y*.13));line(pts,0xc7a8ff);const p=sphere(.17,glow(chargeSign>0?0xf0df73:0x78a8ff,.5),pts[0].x,pts[0].y,pts[0].z,22);const f=arrow(new THREE.Vector3(0,0,Math.sign(values.I||1)),new THREE.Vector3(.2,.35,0),1.45,0x78e6a1);modelState={beads,pts,p,chargeSign,f};setReadout([`Fwire = ${fmt(values.B*values.I*.08)} N`,`particle radius ∝ mv/(BQ)`,`reversing charge or B reverses curvature direction`])}
  function buildInduction(){const coilMat=glow(0xd47a35,.18),n=Math.max(5,Math.round(values.turns/45)),rings=[];for(let i=0;i<n;i++)rings.push(torus(1.55,.055,coilMat,1.5+(i-n/2)*.12,0,0,0));const magnetGroup=new THREE.Group();const red=new THREE.Mesh(new THREE.CylinderGeometry(.68,.68,1.65,30),mat(0xb94c4c,.34,.08));red.rotation.z=Math.PI/2;red.position.x=.82;const blue=new THREE.Mesh(new THREE.CylinderGeometry(.68,.68,1.65,30),mat(0x4f74c5,.34,.08));blue.rotation.z=Math.PI/2;blue.position.x=-.82;magnetGroup.add(red,blue);modelRoot.add(magnetGroup);magnetGroup.position.x=-3.2;const lamp=sphere(.28,glow(0x7fe6a7,.05),4.2,0,0);modelState={rings,coilMat,magnetGroup,lamp,speed:values.speed,strength:values.strength,turns:values.turns};setReadout([`relative εpeak ∝ N × rate of flux change`,`turns ${values.turns.toFixed(0)} · strength ${values.strength.toFixed(1)}`,`watch coil/lamp brightness track |d(NΦ)/dt|`])}
  function corePoint(u){const pts=[new THREE.Vector3(-2.7,2.2,0),new THREE.Vector3(2.7,2.2,0),new THREE.Vector3(2.7,-2.2,0),new THREE.Vector3(-2.7,-2.2,0)];const seg=(u*4)%4,i=Math.floor(seg),t=seg-i,a=pts[i],b=pts[(i+1)%4];return a.clone().lerp(b,t)}
  function buildTransformer(){const core=mat(0x66717f,.52,.62);box(6,.65,.9,core,0,2.2,0);box(6,.65,.9,core,0,-2.2,0);box(.65,4.4,.9,core,-2.7,0,0);box(.65,4.4,.9,core,2.7,0,0);const pMat=glow(0xd47a35,.15),sMat=glow(0x5eafe0,.15),pTurns=Math.max(5,Math.round(values.Np/90)),sTurns=Math.max(5,Math.round(values.Ns/140));for(let i=0;i<pTurns;i++)torus(.72,.045,pMat,-2.7,-1.5+i*(3/(pTurns-1||1)),0,Math.PI/2);for(let i=0;i<sTurns;i++)torus(.72,.045,sMat,2.7,-1.5+i*(3/(sTurns-1||1)),0,Math.PI/2);const flux=[];for(let i=0;i<18;i++){const p=corePoint(i/18);flux.push(sphere(.065,glow(0x74dfff,.7),p.x,p.y,.62,14))}const load=box(1.45,1.1,1.35,glow(0x183d5b,.1),5.2,0,0),Vs=values.Vp*values.Ns/values.Np,Is=values.power/Math.max(Vs,.1),loss=Is*Is*values.lineR;modelState={pMat,sMat,flux,load,Vs,Is,loss};setReadout([`Vs ≈ ${fmt(Vs)} V`,`Is ≈ ${fmt(Is)} A · line loss ≈ ${fmt(loss)} W`,`turns ratio ${(values.Ns/values.Np).toFixed(2)}`])}
  function buildWire(){box(2.0,2.15,4.6,mat(0xbd4d4d,.42,.08),0,1.5,0);box(2.0,2.15,4.6,mat(0x4d73bd,.42,.08),0,-1.5,0);for(let x=-2.4;x<=2.4;x+=1.0)for(let z=-1.5;z<=1.5;z+=1)arrow(new THREE.Vector3(0,-1,0),new THREE.Vector3(x,1.05,z),2.05,0x68cfff);const wire=cyl(.09,5.2,mat(0xd47a35,.22,.86),0,0,0,'x'),beads=[];for(let i=0;i<11;i++)beads.push(sphere(.065,glow(0xf2c86b,.65),-2.5+i*.48,.16,0,16));const pan=box(4.8,.22,3.3,mat(0x7d8793,.42,.55),0,-2.45,0),F=values.B*values.I*values.L,f=arrow(new THREE.Vector3(0,0,Math.sign(values.I||1)),new THREE.Vector3(0,.35,0),Math.min(1.8,.7+Math.abs(F)*35),0x78e6a1);modelState={wire,beads,pan,f,F};setReadout([`F = BIL = ${fmt(F)} N`,`apparent mass change ≈ ${fmt(Math.abs(F)/9.81*1000)} g`,`reverse I → reverse force direction`])}
  function buildCoil(){box(1.7,4.7,4.5,mat(0xbd4d4d,.42,.08),-3.8,0,0);box(1.7,4.7,4.5,mat(0x4d73bd,.42,.08),3.8,0,0);for(let y=-1.7;y<=1.7;y+=.85)for(let z=-1.5;z<=1.5;z+=1)arrow(new THREE.Vector3(1,0,0),new THREE.Vector3(-2.7,y,z),5.4,0x68cfff);const coil=new THREE.Group(),wireMat=glow(0xd47a35,.18);const w=2.8,h=2.2;const segments=[[[ -w/2,-h/2,0],[w/2,-h/2,0]],[[w/2,-h/2,0],[w/2,h/2,0]],[[w/2,h/2,0],[-w/2,h/2,0]],[[-w/2,h/2,0],[-w/2,-h/2,0]]];for(let n=0;n<4;n++){const off=(n-1.5)*.05;segments.forEach(s=>{const a=new THREE.Vector3(...s[0]),b=new THREE.Vector3(...s[1]);a.z+=off;b.z+=off;const mid=a.clone().add(b).multiplyScalar(.5),len=a.distanceTo(b),o=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,len,12),wireMat);o.position.copy(mid);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());coil.add(o)})}modelRoot.add(coil);const led=sphere(.24,glow(0x78e6a1,.05),0,-2.0,2.8);modelState={coil,wireMat,led,start:values.angle*Math.PI/180,speed:values.sweep*Math.PI/180,B:values.B,N:values.N,A:values.area*1e-4};setReadout([`NΦ = BAN cosθ`,`B ${values.B.toFixed(2)} T · N ${values.N.toFixed(0)} · A ${values.area.toFixed(0)} cm²`,`rotation shows flux-linkage/emf phase relationship`])}
  function build(){clearModel();titleEl.textContent=defs[mode].name;descEl.textContent=defs[mode].desc;if(mode==='orbit')buildOrbit();else if(mode==='electric')buildElectric();else if(mode==='capacitor')buildCapacitor();else if(mode==='magnetic')buildMagnetic();else if(mode==='induction')buildInduction();else if(mode==='transformer')buildTransformer();else if(mode==='wire')buildWire();else buildCoil();updateVectorsVisibility()}
  function renderControls(){controlsHost.innerHTML='';defs[mode].controls.forEach(c=>{const wrap=document.createElement('label');wrap.className='field';if(c[2]==='select'){wrap.innerHTML=`<span>${c[1]}</span><select>${c[3].map(o=>`<option value="${o[0]}" ${values[c[0]]===o[0]?'selected':''}>${o[1]}</option>`).join('')}</select>`;const i=wrap.querySelector('select');i.oninput=()=>{values[c[0]]=i.value;scheduleBuild()}}else{wrap.innerHTML=`<span>${c[1]}</span><input type="range" min="${c[2]}" max="${c[3]}" step="${c[4]}" value="${values[c[0]]}"><output>${values[c[0]]}</output>`;const i=wrap.querySelector('input'),o=wrap.querySelector('output');i.oninput=()=>{values[c[0]]=Number(i.value);o.textContent=i.value;scheduleBuild()}}controlsHost.appendChild(wrap)})}
  let buildRAF=0;function scheduleBuild(){cancelAnimationFrame(buildRAF);buildRAF=requestAnimationFrame(()=>{build();elapsed=0})}
  function setupTabs(){tabs.innerHTML='';Object.entries(defs).forEach(([id,d])=>{const b=document.createElement('button');b.className='button'+(id===mode?' primary':'');b.textContent=d.name;b.onclick=()=>{mode=id;values=defaults();elapsed=0;build();renderControls();setupTabs()};tabs.appendChild(b)})}
  function updateVectorsVisibility(){modelRoot.traverse(o=>{if(o.isArrowHelper)o.visible=vectors})}
  function update(dt){if(!playing)return;elapsed+=dt;if(mode==='orbit'){const s=modelState,a=elapsed*.48*s.speedFactor,x=s.orbitR*Math.cos(a),z=s.orbitR*Math.sin(a);s.sat.position.set(x,0,z);s.sat.rotation.y=-a;s.planet.rotation.y+=dt*.1;s.f.position.set(x,0,z);s.f.setDirection(new THREE.Vector3(-Math.cos(a),0,-Math.sin(a)));s.vv.position.set(x,0,z);s.vv.setDirection(new THREE.Vector3(-Math.sin(a),0,Math.cos(a)))}
    else if(mode==='electric'){const s=modelState,u=(elapsed*.22*s.launch)%1;s.particle.position.set(s.sign*.95*u*u,0,-2.8+5.6*u);s.markers.forEach((m,i)=>{const p=(elapsed*.65+m.off)%1;m.s.position.x=-s.gap+.3+p*(2*s.gap-.6);m.s.scale.setScalar(.75+.35*Math.sin(elapsed*4+i))})}
    else if(mode==='capacitor'){const s=modelState,tau=Math.max(.08,s.tau),p=s.mode==='charge'?1-Math.exp(-elapsed/tau):Math.exp(-elapsed/tau),Vc=s.V0*p,I=(s.V0/(values.R*1e3))*Math.exp(-elapsed/tau);s.plus.forEach(o=>{o.material.emissiveIntensity=.12+.8*p;o.scale.setScalar(.65+.35*p)});s.minus.forEach(o=>{o.material.emissiveIntensity=.12+.8*p;o.scale.setScalar(.65+.35*p)});s.beads.forEach((b,i)=>{const q=(elapsed*Math.max(.15,Math.abs(I)*2500)+i/s.beads.length)%1;b.position.x=-1.5+3*q;b.material.emissiveIntensity=.25+1.2*Math.abs(I)*1000});if(performance.now()-lastRead>120)setReadout([`Vcapacitor ≈ ${fmt(Vc)} V`,`I ≈ ${fmt(I)} A · τ ${fmt(tau)} s`,`${s.mode} progress ${Math.round(p*100)}%`])}
    else if(mode==='magnetic'){const s=modelState,dir=Math.sign(values.I||1);s.beads.forEach((b,i)=>{const u=(elapsed*Math.max(.15,Math.abs(values.I))*.25+i/s.beads.length)%1;b.position.x=dir>0?-2.4+4.8*u:2.4-4.8*u});const u=(elapsed*.23*(values.speed/2))%1,idx=Math.floor(u*(s.pts.length-1));s.p.position.copy(s.pts[idx]);s.p.material.emissiveIntensity=.35+.35*Math.sin(elapsed*5);if(s.f)s.f.visible=vectors&&Math.abs(values.I)>.05}
    else if(mode==='induction'){const s=modelState,x=-3.2+Math.sin(elapsed*s.speed*1.5)*2.35,vx=Math.cos(elapsed*s.speed*1.5)*2.35*s.speed*1.5;s.magnetGroup.position.x=x;const em=Math.min(2.5,Math.abs(vx)*s.strength*s.turns/220);s.coilMat.emissive.setHex(vx>=0?0x5fbfff:0xf2a45e);s.coilMat.emissiveIntensity=.08+em*.45;s.lamp.material.emissive.setHex(vx>=0?0x76e6a1:0xf2c86b);s.lamp.material.emissiveIntensity=.05+em*.8;s.lamp.scale.setScalar(.9+Math.min(.45,em*.12));if(performance.now()-lastRead>120)setReadout([`relative ε ≈ ${fmt(vx*s.strength*s.turns*.003)} V`,`magnet velocity ${fmt(vx)} relative units`,`direction reverses as magnet reverses motion`])}
    else if(mode==='transformer'){const s=modelState,ph=elapsed*2.6,amp=.15+.55*Math.abs(Math.sin(ph));s.pMat.emissiveIntensity=amp;s.sMat.emissiveIntensity=.1+amp*(values.Ns/values.Np>1?1:.7);s.flux.forEach((b,i)=>{const p=corePoint((i/s.flux.length+elapsed*.12)%1);b.position.copy(p);b.material.emissiveIntensity=.25+1.0*Math.abs(Math.sin(ph))});s.load.material.emissive.setHex(0x4fb77a);s.load.material.emissiveIntensity=.12+.55*Math.abs(Math.sin(ph))}
    else if(mode==='wire'){const s=modelState,dir=Math.sign(values.I||1),speed=Math.max(.08,Math.abs(values.I)*.18);s.beads.forEach((b,i)=>{const u=(elapsed*speed+i/s.beads.length)%1;b.position.x=dir>=0?-2.5+5*u:2.5-5*u});s.pan.position.y=-2.45+.025*Math.sin(elapsed*4)*Math.min(1,Math.abs(s.F)*30);s.wire.position.z=.02*Math.sin(elapsed*5)*Math.sign(s.F||1);s.f.visible=vectors&&Math.abs(values.I)>.03}
    else if(mode==='coil'){const s=modelState,theta=s.start+elapsed*s.speed;s.coil.rotation.y=theta;const flux=s.N*s.B*s.A*Math.cos(theta),emf=s.N*s.B*s.A*s.speed*Math.sin(theta);s.wireMat.emissiveIntensity=.08+Math.min(1.4,Math.abs(emf)*18);s.led.material.emissiveIntensity=.05+Math.min(1.8,Math.abs(emf)*20);if(performance.now()-lastRead>120)setReadout([`NΦ = ${fmt(flux)} Wb turn`,`ε ≈ ${fmt(emf)} V`,`θ = ${fmt((theta*180/Math.PI)%360)}°`])}lastRead=performance.now()}
  function resize(){const r=stage.getBoundingClientRect();if(r.width<10||r.height<10)return;renderer.setPixelRatio(qualityPixel);renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}
  const ro=new ResizeObserver(()=>requestAnimationFrame(resize));ro.observe(stage);window.addEventListener('resize',()=>requestAnimationFrame(resize));
  new IntersectionObserver(es=>{visible=!!es[0]?.isIntersecting},{threshold:.03}).observe(section);document.addEventListener('visibilitychange',()=>{if(document.hidden)last=performance.now()});
  let qualityCooldown=0;function loop(now){requestAnimationFrame(loop);if(!visible||document.hidden){last=now;return}const dt=Math.min(.033,Math.max(.001,(now-last)/1000));last=now;update(dt);renderer.render(scene,camera);fps.push(1/dt);if(fps.length>90)fps.shift();if(now-qualityCooldown>5000&&fps.length>50){const avg=fps.reduce((a,b)=>a+b,0)/fps.length,target=Math.min(window.devicePixelRatio||1,2);let changed=false;if(avg<38&&qualityPixel>1){qualityPixel=Math.max(1,qualityPixel-.25);changed=true}else if(avg>55&&qualityPixel<target){qualityPixel=Math.min(target,qualityPixel+.25);changed=true}if(changed){qualityCooldown=now;resize()}fpsEl.textContent=`${Math.round(avg)} fps · ${qualityPixel.toFixed(2)}× render`;fpsEl.className='pill '+(avg>45?'three-v9-status-good':'three-v9-status-mid')}}
  section.querySelector('#threeV9Play').onclick=e=>{playing=!playing;e.currentTarget.textContent=playing?'Pause':'Play';e.currentTarget.classList.toggle('primary',playing);stateEl.textContent=playing?'Playing':'Paused'};
  section.querySelector('#threeV9Reset').onclick=()=>{values=defaults();elapsed=0;build();renderControls()};section.querySelector('#threeV9Camera').onclick=()=>{yaw=-.58;pitch=.34;distance=15;updateCamera()};section.querySelector('#threeV9Vectors').onclick=e=>{vectors=!vectors;e.currentTarget.textContent='Vectors '+(vectors?'on':'off');e.currentTarget.classList.toggle('primary',vectors);updateVectorsVisibility()};
  values=defaults();setupTabs();renderControls();build();resize();requestAnimationFrame(loop);
}
